name: matrix Update

permissions:
  contents: write
  actions: write

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

concurrency:
  group: daily-update
  cancel-in-progress: false

jobs:

# --------------------------------
# STEP 1
# อ่าน categories.json
# --------------------------------
  prepare:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:

      - uses: actions/checkout@v4

      - name: Generate Matrix
        id: set-matrix
        run: |

          MATRIX=$(node -e "
          const cats=require('./data/categories.json');
          console.log(JSON.stringify({
            category: cats.map(c=>c.slug)
          }));
          ")

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT


# --------------------------------
# STEP 2
# scraper
# --------------------------------
  update:

    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 355

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci


# -------------------------------
# RUN SCRAPER
# -------------------------------
      - name: Run Scraper
        id: scraper
        run: |

          echo "RUN CATEGORY: ${{ matrix.category }}"

          node update.js ${{ matrix.category }} | tee output.txt

          if grep -q "SCRAPER_STATUS:IN_PROGRESS" output.txt; then
            echo "continue=true" >> $GITHUB_OUTPUT
          else
            echo "continue=false" >> $GITHUB_OUTPUT
          fi


# -------------------------------
# COMMIT
# -------------------------------
      - name: Commit Data
        run: |

          git config --global user.name "auto-bot"
          git config --global user.email "auto@bot.com"

          git add data/*.json || true

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "update ${{ matrix.category }}"

            for i in {1..5}; do
              git pull --rebase origin main && git push && break
              echo "Retry push..."
              sleep 5
            done
          fi


# -------------------------------
# TRIGGER NEXT RUN
# -------------------------------
      - name: Trigger Next Run
        if: steps.scraper.outputs.continue == 'true'
        run: |

          echo "Trigger next workflow..."

          gh workflow run matrix.yml

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
