name: SeriesDay Scraper

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape:all

      - name: Commit data update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "auto update data"
            git push
          fi
