name: SeriesDay Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: scraper
  cancel-in-progress: false

jobs:

  scrape:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        category:
          - chinese
          - korean
          - japanese
          - thai
          - new
          - y
          - western
          - netflix

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      # -------------------
      # SERIES
      # -------------------

      - name: Run Series Scraper
        run: node scraper-category.js ${{ matrix.category }}

      - name: Commit Series
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/series

          if git diff --cached --quiet; then
            echo "No series changes"
          else
            git commit -m "update series ${{ matrix.category }}"
            git pull --rebase
            git push || (sleep 5 && git pull --rebase && git push)
          fi

      # -------------------
      # EPISODES
      # -------------------

      - name: Run Episodes Scraper
        run: node episodes.js ${{ matrix.category }}

      - name: Commit Episodes
        run: |
          git add data/episodes data/progress

          if git diff --cached --quiet; then
            echo "No episodes changes"
          else
            git commit -m "update episodes ${{ matrix.category }}"
            git pull --rebase
            git push || (sleep 5 && git pull --rebase && git push)
          fi

      # -------------------
      # PLAYERS
      # -------------------

      - name: Run Players Scraper
        run: node players.js ${{ matrix.category }}

      - name: Commit Playlist
        run: |
            git add data/playlist data/progress

            if git diff --cached --quiet; then
              echo "No playlist changes"
            else
              git commit -m "update playlist ${{ matrix.category }}"
              git pull --rebase
              git push || (sleep 5 && git pull --rebase && git push)
            fi  

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install gh -y

      - name: Re-run workflow before timeout
        run: |
          echo "Waiting before re-run..."
          sleep 20000
          gh workflow run "${{ github.workflow }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
